### PR TITLE
Prettier formatter and pre-commit hook added

### PR DESCRIPTION
**Pull request by rajatdhoot123**
Huskey Integrated for the pre-commit hook with prettier formatting so all the contributors have the same formatted code before pushing so we are able to check diff more accurately and the same formatted code will push into the production irrespective of code editor settings

It might solve the first point of the issue
https://github.com/indiainvestments/indiainvestments.github.io/issues/22#issue-804320069

### CODE REVIEW

**Comment by crimelabs786** [comment]
Hi @rajatdhoot123, thanks for submitting this PR.

We'd appreciate if you'd have informed us or talked to someone in our Discord before raising this PR.

In any case, I already have a PR open on another repo, and would've ported that here when needed: https://github.com/indiainvestments/faq-to-discord-action/pull/2

This repository does not need Prettier at the moment, it has only a single config file that uses JS. Most of the JS / TS stuff, for now, is in another repository. This is mostly going to be a repository of Markdown files, with some JSON / YAML config files.

---

As for the issue you've linked, it's to investigate & estimate the builds and check if we're remaining below free quota. But not to actually add the builds.

Please don't be disheartened, we appreciate your inputs & effort. But do talk to us on Discord or Reddit or even in the issue comments section, before raising any pull requests.

**Comment by rajatdhoot123** [comment]
Totally fine but why we are not using prettier markdowns for any particular reason because if there are many contributors then their way of writing will be different and then visualizing diff becomes hard.

**Comment by crimelabs786** [comment]
@rajatdhoot123 ok, please send a PR that adds PR, and uses `lint-staged` to prettify markdown, YAML, JS, and JSON file. Don't add any action yet.

**Comment by rajatdhoot123** [comment]
Don't add any action yet -> like no pre-commit hook...?

**Comment by crimelabs786** [comment]
@rajatdhoot123 no, a pre-commit hook is fine. Don't add any GitHub action in workflow yet.

**Comment by rajatdhoot123** [comment]
Cool there is no git hub action added simple code formatting on pre-commit nothing else will raise PR

**Pull request closed without merging**
